apiVersion: v1
kind: Service
metadata: 
  name: zookeeper-service
  namespace: apache-kafka-zookeeper 
  labels:
    name: zookeeper-service
spec:
  type: NodePort
  ports:
    - name: zookeeper-port
      port: 2181
      nodePort: 30181
      targetPort: 2181
  selector:
    app: zookeeper-app
