apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker
  name: kafka-service
  namespace: apache-kafka-zookeeper
spec:
  ports:
  - name: port1
    protocol: TCP
    port: 9092
    targetPort: 9092
  - name: port2
    protocol: TCP
    port: 9093
    targetPort: 9093
  selector:
    app: kafka-broker 
