apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
  namespace: apache-kafka-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      hostname: kafka-broker
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_ENABLE_KRAFT
          value: "no"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181"
        - name: KAFKA_CFG_LISTENERS
          value: "INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "INTERNAL://:9093,EXTERNAL://kafka-service:9092"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME  
          value: INTERNAL
        image: docker.io/bitnami/kafka:3.4 
        name: kafka-broker
        ports:
          - containerPort: 9092
          - containerPort: 9093
