apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-dashboard 
  namespace: apache-kafka-zookeeper 
  labels:
    name: kafka-dashboard 
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: kafka-dashboard 
  template:
    metadata:
      labels:
        app: kafka-dashboard 
    spec:
      containers:
        - image: provectuslabs/kafka-ui:latest
          name: kafka-dashboard 
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "Kafka"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka-service:9092"
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"
